var PROVIDER_ID = "dizilla";
var PROVIDER_NAME = "Dizilla";
var PLUGIN_NAME = "Dizilla";
var INCLUDE_JAPANESE = false;

var WATCHBUDDY_BASE_URL = "https://stream.watchbuddy.tv/api/v1";
var TMDB_API_BASE_URL = "https://api.themoviedb.org/3";
var TMDB_API_KEY = "4ef0d7355d9ffb5151e987764708ce96";

var DEFAULT_HEADERS = {
  "Accept": "application/json,text/plain,*/*",
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
};

function mergeObjects(base, extra) { var result = {}; var key; for (key in base) result[key] = base[key]; for (key in (extra || {})) result[key] = extra[key]; return result; }
function fetchJson(url, options) { return fetch(url, { method: options && options.method ? options.method : "GET", headers: mergeObjects(DEFAULT_HEADERS, options && options.headers ? options.headers : null), body: options && options.body ? options.body : void 0 }).then(function(response) { return response.text().then(function(text) { if (!response.ok) throw new Error("Request failed: " + response.status + " " + response.statusText); try { return JSON.parse(text); } catch (error) { throw new Error("JSON parse failed: " + error.message); } }); }); }
function buildQueryString(params) { var pairs = []; var key; for (key in (params || {})) { if (params[key] != null && params[key] !== "") pairs.push(encodeURIComponent(key) + "=" + encodeURIComponent(String(params[key]))); } return pairs.join("&"); }
function buildApiUrl(pathname, params) { var query = buildQueryString(params); return WATCHBUDDY_BASE_URL + "/" + pathname + (query ? "?" + query : ""); }
function decodeWatchBuddyUrl(value) { var current = String(value || "").trim(); var index; if (!current) return ""; for (index = 0; index < 3; index += 1) { try { var decoded = decodeURIComponent(current); if (decoded === current) break; current = decoded; } catch (_error) { break; } } return current; }
function extractYear(dateValue) { if (!dateValue || typeof dateValue !== "string") return null; return Number(dateValue.slice(0, 4)) || null; }
function padNumber(value) { var text = String(value); return text.length < 2 ? "0" + text : text; }
function asciiFold(value) { return String(value || "").replace(/İ/g, "I").replace(/ı/g, "i").replace(/Ş/g, "S").replace(/ş/g, "s").replace(/Ğ/g, "G").replace(/ğ/g, "g").replace(/Ü/g, "U").replace(/ü/g, "u").replace(/Ö/g, "O").replace(/ö/g, "o").replace(/Ç/g, "C").replace(/ç/g, "c"); }
function normalizeText(value) { var text = asciiFold(value); if (text.normalize) text = text.normalize("NFKD").replace(/[\u0300-\u036f]/g, ""); return text.toLowerCase().replace(/&/g, " and ").replace(/[“”"'`’]/g, "").replace(/\([^)]*\)/g, " ").replace(/\b(tv series|season|sezon|episode|bolum|bölüm|movie|film)\b/g, " ").replace(/[:/|._,-]+/g, " ").replace(/\s+/g, " ").trim(); }
function uniqueStrings(values) { var seen = {}; var result = []; var index; for (index = 0; index < (values || []).length; index += 1) { var item = String(values[index] || "").trim(); if (!item || seen[item]) continue; seen[item] = true; result.push(item); } return result; }
function splitTitleVariants(title) { var source = String(title || "").trim(); var variants; var dashParts; var colonParts; var slashParts; var index; if (!source) return []; variants = [source, source.replace(/\([^)]*\)/g, " ").replace(/\s+/g, " ").trim()]; dashParts = source.split(/\s+-\s+/g); colonParts = source.split(/\s*:\s*/g); slashParts = source.split(/\s*\/\s*/g); for (index = 0; index < dashParts.length; index += 1) if (dashParts[index]) variants.push(dashParts[index].trim()); for (index = 0; index < colonParts.length; index += 1) if (colonParts[index]) variants.push(colonParts[index].trim()); for (index = 0; index < slashParts.length; index += 1) if (slashParts[index]) variants.push(slashParts[index].trim()); return uniqueStrings(variants); }
function buildQueryVariants(metadata) { var queries = []; var titleIndex; var variantIndex; for (titleIndex = 0; titleIndex < metadata.titles.length; titleIndex += 1) { var variants = splitTitleVariants(metadata.titles[titleIndex]); for (variantIndex = 0; variantIndex < variants.length; variantIndex += 1) { var variant = variants[variantIndex]; if (variant) { queries.push(variant); queries.push(variant.replace(/\bthe\b/gi, "").replace(/\s+/g, " ").trim()); } } } return uniqueStrings(queries).filter(function(value) { return value.length >= 2; }).sort(function(left, right) { return right.length - left.length; }).slice(0, 6); }
function tokenObject(value) { var tokens = {}; var parts = normalizeText(value).split(" "); var index; for (index = 0; index < parts.length; index += 1) if (parts[index]) tokens[parts[index]] = true; return tokens; }
function objectSize(input) { var size = 0; var key; for (key in input) size += 1; return size; }
function titleSimilarity(left, right) { var leftText = normalizeText(left); var rightText = normalizeText(right); var leftTokens; var rightTokens; var union = {}; var token; var intersection = 0; if (!leftText || !rightText) return 0; if (leftText === rightText) return 1; if (leftText.indexOf(rightText) >= 0 || rightText.indexOf(leftText) >= 0) return 0.9; leftTokens = tokenObject(leftText); rightTokens = tokenObject(rightText); for (token in leftTokens) { union[token] = true; if (rightTokens[token]) intersection += 1; } for (token in rightTokens) union[token] = true; return intersection / Math.max(1, objectSize(union)); }
function bestSimilarity(candidateTitle, metadataTitles) { var best = 0; var candidateVariants = splitTitleVariants(candidateTitle); var candidateIndex; var titleIndex; var metadataVariants; var metadataIndex; for (candidateIndex = 0; candidateIndex < candidateVariants.length; candidateIndex += 1) { for (titleIndex = 0; titleIndex < metadataTitles.length; titleIndex += 1) { metadataVariants = splitTitleVariants(metadataTitles[titleIndex]); for (metadataIndex = 0; metadataIndex < metadataVariants.length; metadataIndex += 1) best = Math.max(best, titleSimilarity(candidateVariants[candidateIndex], metadataVariants[metadataIndex])); } } return best; }
function fetchTmdbMetadata(tmdbId, mediaType) { var languages = INCLUDE_JAPANESE ? ["tr-TR", "en-US", "ja-JP"] : ["tr-TR", "en-US"]; var typeSegment = mediaType === "movie" ? "movie" : "tv"; return Promise.all(languages.map(function(language) { var url = TMDB_API_BASE_URL + "/" + typeSegment + "/" + encodeURIComponent(String(tmdbId)) + "?language=" + encodeURIComponent(language) + "&api_key=" + encodeURIComponent(TMDB_API_KEY); return fetchJson(url).catch(function() { return null; }); })).then(function(results) { var titles = []; var year = null; var index; for (index = 0; index < results.length; index += 1) { if (!results[index]) continue; if (results[index].title) titles.push(results[index].title); if (results[index].name) titles.push(results[index].name); if (results[index].original_title) titles.push(results[index].original_title); if (results[index].original_name) titles.push(results[index].original_name); if (!year) year = extractYear(results[index].release_date || results[index].first_air_date); } titles = uniqueStrings(titles); if (!titles.length) throw new Error("TMDB metadata cozulmedi: " + tmdbId); return { tmdbId: String(tmdbId), mediaType: mediaType, year: year, titles: titles, displayTitle: titles[0] }; }); }
function searchPlugin(query) { return fetchJson(buildApiUrl("search", { plugin: PLUGIN_NAME, query: query })).then(function(payload) { return Array.isArray(payload.result) ? payload.result.map(function(entry) { return { title: entry.title || "", url: decodeWatchBuddyUrl(entry.url), poster: entry.poster || "" }; }).filter(function(entry) { return entry.title && entry.url; }) : []; }); }
function loadItem(encodedUrl) { return fetchJson(buildApiUrl("load_item", { plugin: PLUGIN_NAME, encoded_url: encodedUrl })).then(function(payload) { var result = payload.result; if (!result) return null; result.url = decodeWatchBuddyUrl(result.url); if (Array.isArray(result.episodes)) { result.episodes = result.episodes.map(function(entry) { return { season: entry.season, episode: entry.episode, title: entry.title, url: decodeWatchBuddyUrl(entry.url) }; }); } return result; }); }
function loadLinks(encodedUrl) { return fetchJson(buildApiUrl("load_links", { plugin: PLUGIN_NAME, encoded_url: encodedUrl })).then(function(payload) { return Array.isArray(payload.result) ? payload.result : []; }); }
function dedupeCandidates(candidates) { var byUrl = {}; var index; for (index = 0; index < candidates.length; index += 1) { if (!candidates[index].url) continue; if (!byUrl[candidates[index].url] || byUrl[candidates[index].url].searchScore < candidates[index].searchScore) byUrl[candidates[index].url] = candidates[index]; } return Object.keys(byUrl).map(function(key) { return byUrl[key]; }).sort(function(left, right) { return right.searchScore - left.searchScore; }); }
function searchCandidates(metadata) { var queries = buildQueryVariants(metadata); var aggregated = []; var chain = Promise.resolve(); queries.forEach(function(query) { chain = chain.then(function() { if (aggregated.length >= 15) return null; return searchPlugin(query).then(function(results) { var index; for (index = 0; index < results.length; index += 1) { results[index].searchScore = bestSimilarity(results[index].title, metadata.titles) * 100; aggregated.push(results[index]); } }).catch(function(error) { console.warn("[" + PROVIDER_NAME + "] search failed for '" + query + "': " + error.message); }); }); }); return chain.then(function() { return dedupeCandidates(aggregated); }); }
function findEpisode(item, season, episode) { var index; if (!item || !Array.isArray(item.episodes)) return null; for (index = 0; index < item.episodes.length; index += 1) { if (Number(item.episodes[index].season) === Number(season) && Number(item.episodes[index].episode) === Number(episode)) return item.episodes[index]; } return null; }
function scoreItem(item, metadata, searchScore, mediaType, season, episode) { var score = searchScore + bestSimilarity(item.title || "", metadata.titles) * 35; var difference; var hasEpisodes = Array.isArray(item.episodes) && item.episodes.length > 0; if (metadata.year && item.year) { difference = Math.abs(Number(metadata.year) - Number(item.year)); if (difference === 0) score += 20; else if (difference === 1) score += 8; else score -= 20; } if (mediaType === "tv") { score += hasEpisodes ? 15 : -15; if (season != null && episode != null) score += findEpisode(item, season, episode) ? 40 : -30; } else { score += hasEpisodes ? -15 : 15; } return score; }
function resolvePlayableTarget(metadata, candidates, season, episode) { var best = null; var chain = Promise.resolve(); candidates.slice(0, 6).forEach(function(candidate) { chain = chain.then(function() { return loadItem(candidate.url).then(function(item) { var target; var episodeEntry; if (!item || !item.url) return null; target = { item: item, targetUrl: item.url, itemScore: scoreItem(item, metadata, candidate.searchScore, metadata.mediaType, season, episode) }; if (metadata.mediaType === "tv") { episodeEntry = findEpisode(item, season, episode); if (!episodeEntry || !episodeEntry.url) return null; target.targetUrl = episodeEntry.url; } if (!best || target.itemScore > best.itemScore) best = target; return null; }).catch(function(error) { console.warn("[" + PROVIDER_NAME + "] load_item failed for '" + candidate.url + "': " + error.message); }); }); }); return chain.then(function() { return best; }); }
function extractQuality(name) { var match = String(name || "").match(/(2160p|1080p|720p|480p|360p|4k)/i); return match ? String(match[1]).toUpperCase() : "Auto"; }
function mapStreams(metadata, links, season, episode) { var episodeTag = season != null && episode != null ? "S" + padNumber(season) + "E" + padNumber(episode) : ""; return links.filter(function(link) { return link && link.url; }).map(function(link) { var headers = {}; var titleParts = [metadata.displayTitle]; if (episodeTag) titleParts.push(episodeTag); if (link.name) titleParts.push(link.name); if (link.referer) headers.Referer = link.referer; if (link.user_agent) headers["User-Agent"] = link.user_agent; return { name: link.name ? PROVIDER_NAME + " - " + link.name : PROVIDER_NAME, title: titleParts.join(" - "), url: link.url, quality: extractQuality(link.name), headers: headers, provider: PROVIDER_ID }; }); }
function getStreams(tmdbId, mediaType, season, episode) { return fetchTmdbMetadata(tmdbId, mediaType).then(function(metadata) { return searchCandidates(metadata).then(function(candidates) { if (!candidates.length) { console.warn("[" + PROVIDER_NAME + "] no candidates found for " + metadata.displayTitle); return []; } return resolvePlayableTarget(metadata, candidates, season, episode).then(function(target) { if (!target || !target.targetUrl) { console.warn("[" + PROVIDER_NAME + "] no playable target resolved for " + metadata.displayTitle); return []; } return loadLinks(target.targetUrl).then(function(links) { if (!links.length) { console.warn("[" + PROVIDER_NAME + "] no links returned for " + target.targetUrl); return []; } return mapStreams(metadata, links, season, episode); }); }); }); }).catch(function(error) { console.error("[" + PROVIDER_NAME + "] provider error: " + error.message); return []; }); }
if (typeof module !== "undefined" && module.exports) { module.exports = { getStreams: getStreams }; } else if (typeof globalThis !== "undefined") { globalThis.getStreams = getStreams; } else if (typeof global !== "undefined") { global.getStreams = getStreams; }
